### ISSUE TITLE
npx create-contentful-app fails on zlib error (v1.2.68)

### ISSUE THREAD

**Issue by MykhailoPryn** [contentful/create-contentful-app#1309]
Hi! I am trying to create a new app using the command: npx create-contentful-app my-app

The output of the command:
`Creating a Contentful app in ~/Work/OP/contentful-apps/my-app.
Error: Failed to create my-app

ZlibError: zlib: unexpected end of file
    at Unzip.write (/Users/mykhailopryn/.npm/_npx/a25b92dfae1d563c/node_modules/degit/dist/index-688c5d50.js:1322:22)
    at Unzip.flush (/Users/mykhailopryn/.npm/_npx/a25b92dfae1d563c/node_modules/degit/dist/index-688c5d50.js:1273:10)
    at Unzip.end (/Users/mykhailopryn/.npm/_npx/a25b92dfae1d563c/node_modules/degit/dist/index-688c5d50.js:1279:10)
    at Unpack.end (/Users/mykhailopryn/.npm/_npx/a25b92dfae1d563c/node_modules/degit/dist/index-688c5d50.js:3989:21)
    at Yallist.<anonymous> (/Users/mykhailopryn/.npm/_npx/a25b92dfae1d563c/node_modules/degit/dist/index-688c5d50.js:903:18)
    at Yallist.forEach (/Users/mykhailopryn/.npm/_npx/a25b92dfae1d563c/node_modules/degit/dist/index-688c5d50.js:240:8)
    at ReadStream.emit (/Users/mykhailopryn/.npm/_npx/a25b92dfae1d563c/node_modules/degit/dist/index-688c5d50.js:900:18)
    at ReadStream.emit (/Users/mykhailopryn/.npm/_npx/a25b92dfae1d563c/node_modules/degit/dist/index-688c5d50.js:3262:22)
    at ReadStream.[maybeEmitEnd] (/Users/mykhailopryn/.npm/_npx/a25b92dfae1d563c/node_modules/degit/dist/index-688c5d50.js:864:12)
    at ReadStream.end (/Users/mykhailopryn/.npm/_npx/a25b92dfae1d563c/node_modules/degit/dist/index-688c5d50.js:744:27) {
  code: 'Z_BUF_ERROR',
  errno: -5,
  recoverable: false,
  file: '/Users/mykhailopryn/.degit/github/contentful/apps/8b60cab1522c33ae4f27efb5fe9ab6222065ffb9.tar.gz',
  cwd: '/Users/mykhailopryn/Work/OP/contentful-apps/my-app',
  tarCode: 'TAR_ABORT'
}`

Npm version: 8.15.0
Node version: v16.15.1

**Comment by martin3walker** [comment]
Hey @MykhailoPryn,

We're taking a look, and will update you soon :)

**Comment by martin3walker** [comment]
Hey @MykhailoPryn,

Can you try removing a the folder at `~/.degit`, and then run the command again? [This issue](https://github.com/Rich-Harris/degit/issues/313) looks like it could be the culprit, and that seems to be the workaround. We use degit to clone the template for your app. 

Please confirm if it works for you :) If so, we'll work on a way of fixing this issue more permanently.
