### ISSUE TITLE
New install of create-contentful-app failing on npm start

### ISSUE THREAD

**Issue by thomasbritton** [contentful/create-contentful-app#138]
Hi,

I have just gone through the tutorial to setup the create-contentful-app and the installation went fine with no issues. When it told me to run `npm start` it just returns me the following error:

```bash
> contentful-visual-ordering@0.1.0 start /mnt/c/Users/Thomas Britton/Documents/code/contentful-visual-ordering
> BROWSER=none react-scripts start

/mnt/c/Users/Thomas Britton/Documents/code/contentful-visual-ordering/node_modules/react-scripts/scripts/utils/verifyTypeScriptSetup.js:239
      appTsConfig.compilerOptions[option] = value;
                                          ^

TypeError: Cannot assign to read only property 'jsx' of object '#<Object>'
    at verifyTypeScriptSetup (/mnt/c/Users/Thomas Britton/Documents/code/contentful-visual-ordering/node_modules/react-scripts/scripts/utils/verifyTypeScriptSetup.js:239:43)
    at Object.<anonymous> (/mnt/c/Users/Thomas Britton/Documents/code/contentful-visual-ordering/node_modules/react-scripts/scripts/start.js:31:1)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! contentful-visual-ordering@0.1.0 start: `BROWSER=none react-scripts start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the contentful-visual-ordering@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/thomasbritton/.npm/_logs/2020-11-21T00_39_03_373Z-debug.log
```

Please note I have not changed _any_ code in the generated project.

I am on Windows 10 using WSL2 and my node version is `12.19.0`

Any ideas as to why this is failing?

Thanks
Thomas

**Comment by Jwhiles** [comment]
Hey @thomasbritton it looks like this issue is coming from create-react-app - and should be fixed when a new version of that project is published. In the meantime there are some potential solutions listed in [this ticket](https://github.com/facebook/create-react-app/issues/10110) on the CRA repo.

**Comment by Jwhiles** [comment]
@thomasbritton could you please try upgrading the version react-scripts in your generated app to [4.0.1](https://www.npmjs.com/package/react-scripts/v/4.0.1). This new version was released today, and should hopefully fix the issue that you're seeing.

**Comment by thomasbritton** [comment]
@Jwhiles that worked, thanks
