### ISSUE TITLE
Issue while creating contentful app

### ISSUE THREAD

**Issue by manikanta6696** [contentful/create-contentful-app#1726]
[Skip to content](https://github.com/contentful/create-contentful-app/issues/new#start-of-content)
https://github.com/contentful
/
[create-contentful-app](https://github.com/contentful/create-contentful-app)

Type / to search

[Code](https://github.com/contentful/create-contentful-app)
Issues
4
Pull requests
5
[Actions](https://github.com/contentful/create-contentful-app/actions)
[Security](https://github.com/contentful/create-contentful-app/security)
[Insights](https://github.com/contentful/create-contentful-app/pulse)
@manikantabudida
Issue while creating contentful app
 

C:\Users\abcd\Desktop>npx create-contentful-app content-migrator
Creating a Contentful app in ~\Desktop\content-migrator.
? Do you want to start with a blank template or use one of our examples? Template
? Pick a template JavaScript

---- Cloning the javascript template...

Error: Failed to create content-migrator

ZlibError: zlib: unexpected end of file
    at Unzip.write (C:\Users\abcd\AppData\Local\npm-cache\_npx\a25b92dfae1d563c\node_modules\degit\dist\index-688c5d50.js:1322:22)
    at Unzip.flush (C:\Users\abcd\AppData\Local\npm-cache\_npx\a25b92dfae1d563c\node_modules\degit\dist\index-688c5d50.js:1273:10)
    at Unzip.end (C:\Users\abcd\AppData\Local\npm-cache\_npx\a25b92dfae1d563c\node_modules\degit\dist\index-688c5d50.js:1279:10)
    at Unpack.end (C:\Users\abcd\AppData\Local\npm-cache\_npx\a25b92dfae1d563c\node_modules\degit\dist\index-688c5d50.js:3989:21)
    at Yallist.<anonymous> (C:\Users\abcd\AppData\Local\npm-cache\_npx\a25b92dfae1d563c\node_modules\degit\dist\index-688c5d50.js:903:18)
    at Yallist.forEach (C:\Users\abcd\AppData\Local\npm-cache\_npx\a25b92dfae1d563c\node_modules\degit\dist\index-688c5d50.js:240:8)
    at ReadStream.emit (C:\Users\abcd\AppData\Local\npm-cache\_npx\a25b92dfae1d563c\node_modules\degit\dist\index-688c5d50.js:900:18)
    at ReadStream.emit (C:\Users\abcd\AppData\Local\npm-cache\_npx\a25b92dfae1d563c\node_modules\degit\dist\index-688c5d50.js:3262:22)
    at ReadStream.[maybeEmitEnd] (C:\Users\abcd\AppData\Local\npm-cache\_npx\a25b92dfae1d563c\node_modules\degit\dist\index-688c5d50.js:864:12)
    at ReadStream.end (C:\Users\abcd\AppData\Local\npm-cache\_npx\a25b92dfae1d563c\node_modules\degit\dist\index-688c5d50.js:744:27) {
  code: 'Z_BUF_ERROR',
  errno: -5,
  recoverable: false,
  file: 'C:\\Users\\abcd\\.degit\\github\\contentful\\apps/a8813aeff43c41e410ac11a0b25c914b57b4c9d2.tar.gz',
  cwd: 'C:\\Users\\abcd\\Desktop\\content-migrator',
  tarCode: 'TAR_ABORT'
}
No file chosen
Attach files by dragging & dropping, selecting or pasting them.
[ Styling with Markdown is supported](https://docs.github.com/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax)
Remember, contributions to this repository should follow its [contributing guidelines](https://github.com/contentful/.github/blob/d26b491e65d5d6f70745cb3b8a7e06f5041baa6f/CONTRIBUTING.md), [security policy](https://github.com/contentful/.github/blob/d26b491e65d5d6f70745cb3b8a7e06f5041baa6f/SECURITY.md), and [code of conduct](https://github.com/contentful/.github/blob/d26b491e65d5d6f70745cb3b8a7e06f5041baa6f/CODE_OF_CONDUCT.md).
Assignees
No one assigned
Labels
None yet
Projects
None yet
Milestone
No milestone
Development
Shows branches and pull requests linked to this issue.

👋

It looks like this is your first time opening an issue in this project!

Be sure to review the [contributing guidelines](https://github.com/contentful/.github/blob/d26b491e65d5d6f70745cb3b8a7e06f5041baa6f/CONTRIBUTING.md) and [code of conduct](https://github.com/contentful/.github/blob/d26b491e65d5d6f70745cb3b8a7e06f5041baa6f/CODE_OF_CONDUCT.md).

Reporting a security vulnerability?
Check out the project's [security policy](https://github.com/contentful/create-contentful-app/security/policy).

Footer
© 2023 GitHub, Inc.
Footer navigation
[Terms](https://docs.github.com/site-policy/github-terms/github-terms-of-service)
[Privacy](https://docs.github.com/site-policy/privacy-policies/github-privacy-statement)
[Security](https://github.com/security)
[Status](https://www.githubstatus.com/)
[Docs](https://docs.github.com/)
[Contact GitHub](https://support.github.com/?tags=dotcom-footer)
[Pricing](https://github.com/pricing)
[API](https://docs.github.com/)
[Training](https://services.github.com/)
[Blog](https://github.blog/)
[About](https://github.com/about)
New Issue · contentful/create-contentful-app

**Comment by jjolton-contentful** [comment]
@manikanta6696 out of curiosity, what node/npm versions are you using? Does it throw this error every time or is there a chance this was a network hiccup? I am currently unable to reproduce this.

**Comment by manikanta6696** [comment]
Seems like the Network issue, Its working now..
It used to work for me earlier too. Received this error for first time.
Now it started working agian.

Thanks :)
