### ISSUE TITLE
create-contentful-app command fails to init a new app

### ISSUE THREAD

**Issue by wuyun117** [contentful/create-contentful-app#1958]
Hello, I've encountered something odd: I cannot init a new Contentful app.

**Steps to reproduce**
npx create-contentful-app my-first-app --yarn

**Expected behavior**
create-contentful-app to build a bootstrapped directory called 'my-first-app'

**Actual behavior**
```
$ npx create-contentful-app my-first-app --yarn
Need to install the following packages:
create-contentful-app@1.3.6
Ok to proceed? (y) y
Creating a Contentful app in ~/Documents/***/***.
? Do you want to start with a blank template or use one of our examples? Template
? Pick a template TypeScript
 
---- Cloning the typescript template...
 
Error: Failed to create my-first-app

DegitError: could not find commit hash for HEAD
    at Degit._cloneWithTar (/Users/xxx/.npm/_npx/a25b92dfae1d563c/node_modules/degit/dist/index-688c5d50.js:14258:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Degit.clone (/Users/xxx/.npm/_npx/a25b92dfae1d563c/node_modules/degit/dist/index-688c5d50.js:14096:4) {
  code: 'MISSING_REF',
  ref: 'HEAD'
}
```

**Init with NPM**
Same error

**Versions**
Node: 18.19.0
Yarn: 1.22.19
NPM: 10.2.3
MacOS:  14.4.1 with Chip M1

**Comment by david-shibley-contentful** [comment]
@wuyun117 I attempted to follow your reproduction steps and everything succeeded. I am using the same version of node, yarn, npm, and MacOS. 

Perhaps try clearing your cache and upgrading the latest version of degit:
1- First clear the npm cache by: npm cache clean --force
2- Upgrade digit to the latest version: npm install -g degit@latest

**Comment by LukePernigotti** [comment]
I'm having the same issue. I tried with different node versions, clearing the npm cache and upgrading digit to the latest version.

**Comment by jimj-procoretech** [comment]
I'm also seeing this behavior. Cleared npm cache and updated degit to latest.
npm v10.2.4
node v21.6.2
macOS v14.2.1

**Comment by wuyun117** [comment]
@david-shibley-contentful Still seeing the same error after Cleared the cache and upgraded the degit version

**Comment by anassalama** [comment]
@david-shibley-contentful I'm still seeing the same error after clearing the cache and upgrading the degit version

**Comment by this-amazing-amy** [comment]
I'm also seeing this error. I'm on node 20.7.0, cleared the cache and upgraded degit.

**Comment by Esmi92** [comment]
Hello I have the same issue I also cleared the cache and is not working, node version is 18.19.1, I don't have `https_proxy` environment variable set.

**Comment by jjolton-contentful** [comment]
@wuyun117 @LukePernigotti @anassalama @this-amazing-amy @Esmi92 @jimj-procoretech this should be resolved on the latest version, can you confirm if `npx create-contentful-app@latest my-app` is working well for you now?

**Comment by anassalama** [comment]
i tried it again and i got a different error this time :
ZlibError: zlib: unexpected end of file
    at Unzip.write (C:\Users\asalama\AppData\Local\npm-cache\_npx\bc8ff14b6d2dca02\node_modules\minizlib\index.js:154:22)
    at Unzip.flush (C:\Users\asalama\AppData\Local\npm-cache\_npx\bc8ff14b6d2dca02\node_modules\minizlib\index.js:105:10)
    at Unzip.end (C:\Users\asalama\AppData\Local\npm-cache\_npx\bc8ff14b6d2dca02\node_modules\minizlib\index.js:111:10)  
    at Unpack.end (C:\Users\asalama\AppData\Local\npm-cache\_npx\bc8ff14b6d2dca02\node_modules\tar\lib\parse.js:544:21)  
    at Pipe.end (C:\Users\asalama\AppData\Local\npm-cache\_npx\bc8ff14b6d2dca02\node_modules\fs-minipass\node_modules\minipass\index.js:75:17)
    at [emitEnd2] (C:\Users\asalama\AppData\Local\npm-cache\_npx\bc8ff14b6d2dca02\node_modules\fs-minipass\node_modules\minipass\index.js:522:9)
    at [emitEnd] (C:\Users\asalama\AppData\Local\npm-cache\_npx\bc8ff14b6d2dca02\node_modules\fs-minipass\node_modules\minipass\index.js:507:21)
    at ReadStream.emit (C:\Users\asalama\AppData\Local\npm-cache\_npx\bc8ff14b6d2dca02\node_modules\fs-minipass\node_modules\minipass\index.js:458:27)
    at ReadStream.emit (C:\Users\asalama\AppData\Local\npm-cache\_npx\bc8ff14b6d2dca02\node_modules\fs-minipass\index.js:175:22)
    at [maybeEmitEnd] (C:\Users\asalama\AppData\Local\npm-cache\_npx\bc8ff14b6d2dca02\node_modules\fs-minipass\node_modules\minipass\index.js:440:12) {
  code: 'Z_BUF_ERROR',
  errno: -5,
  recoverable: false,
  file: 'C:\\Users\\asalama\\.degit\\github\\contentful\\apps/ac44b119a939c719b13c87ae1fe1eadd81b5c85f.tar.gz',
  cwd: 'C:/Users/asalama/Desktop/drupal connector/drupal-connector-app',
  tarCode: 'TAR_ABORT'
}

**Comment by anassalama** [comment]
i tried it again and got a diiferent error this time : 

ZlibError: zlib: unexpected end of file
    at Unzip.write (C:\Users\xxx\AppData\Local\npm-cache\_npx\bc8ff14b6d2dca02\node_modules\minizlib\index.js:154:22)
    at Unzip.flush (C:\Users\xxx\AppData\Local\npm-cache\_npx\bc8ff14b6d2dca02\node_modules\minizlib\index.js:105:10)
    at Unzip.end (C:\Users\xxx\AppData\Local\npm-cache\_npx\bc8ff14b6d2dca02\node_modules\minizlib\index.js:111:10)  
    at Unpack.end (C:\Users\xxx\AppData\Local\npm-cache\_npx\bc8ff14b6d2dca02\node_modules\tar\lib\parse.js:544:21)  
    at Pipe.end (C:\Users\xxx\AppData\Local\npm-cache\_npx\bc8ff14b6d2dca02\node_modules\fs-minipass\node_modules\minipass\index.js:75:17)
    at [emitEnd2] (C:\Users\xxx\AppData\Local\npm-cache\_npx\bc8ff14b6d2dca02\node_modules\fs-minipass\node_modules\minipass\index.js:522:9)
    at [emitEnd] (C:\Users\xxx\AppData\Local\npm-cache\_npx\bc8ff14b6d2dca02\node_modules\fs-minipass\node_modules\minipass\index.js:507:21)
    at ReadStream.emit (C:\Users\xxx\AppData\Local\npm-cache\_npx\bc8ff14b6d2dca02\node_modules\fs-minipass\node_modules\minipass\index.js:458:27)
    at ReadStream.emit (C:\Users\xxx\AppData\Local\npm-cache\_npx\bc8ff14b6d2dca02\node_modules\fs-minipass\index.js:175:22)
    at [maybeEmitEnd] (C:\Users\xxx\AppData\Local\npm-cache\_npx\bc8ff14b6d2dca02\node_modules\fs-minipass\node_modules\minipass\index.js:440:12) {
  code: 'Z_BUF_ERROR',
  errno: -5,
  recoverable: false,
  file: 'C:\\Users\\xxx\\.degit\\github\\contentful\\apps/ac44b119a939c719b13c87ae1fe1eadd81b5c85f.tar.gz',
  cwd: 'C:/Users/xxx/Desktop/folder/my-app',
  tarCode: 'TAR_ABORT'
}

**Comment by LukePernigotti** [comment]
This is now working for me. Thank you @jjolton-contentful

**Comment by jjolton-contentful** [comment]
@anassalama we just made one additional change that should resolve that issue you are seeing, will you please give it one more go at your convenience? 

If that doesn't do the trick, manually clearing your degit cache should also fix things up (`rm -rf ~/.degit`). See https://github.com/tiged/tiged/issues/45 for more details if you are interested, but again hopefully `npx create-contentful-app@latest my-app` will just work for you now :)

**Comment by anassalama** [comment]
Finally it worked, thank you @jjolton-contentful

**Comment by jjolton-contentful** [comment]
@wuyun117 I made a small edit to your original issue description as it was referencing the deprecated "init" mechanism (it was wrong in the "Steps to reproduce" section but right in the "Actual behavior" section 😉) just in case anyone stumbles upon this issue in the future. 

Thanks again for reporting this issue! I am going to close it out but please do feel free to reopen if you are still having any trouble.

**Comment by wuyun117** [comment]
> @wuyun117 I made a small edit to your original issue description as it was referencing the deprecated "init" mechanism (it was wrong in the "Steps to reproduce" section but right in the "Actual behavior" section 😉) just in case anyone stumbles upon this issue in the future.
> 
> Thanks again for reporting this issue! I am going to close it out but please do feel free to reopen if you are still having any trouble.

@jjolton-contentful Yeah, feel free to update it. And thank you, it's working now from my side. That's awesome 👍
